### ISSUE TITLE
Clone feature

### ISSUE THREAD

**Issue by rushter** [lexbor/lexbor#118]
It would be cool to have the clone feature that we have in [Modest](https://github.com/rushter/selectolax/issues/27#issuecomment-668460561).

I want to keep an almost identical interface in selectolax that will support two backends: Modest and Lexbor.
Right now, selectolax also supports document cloning to avoid parsing the same document twice in case you need to modify nodes and keep the original document as well.

**Comment by lexborisov** [comment]
@rushter 

This is a simple task. I'll do it.

**Comment by lexborisov** [comment]
@rushter 

Done.
1. [lxb_dom_node_clone(...)](https://github.com/lexbor/lexbor/blob/master/source/lexbor/dom/interfaces/node.h#L87)
2. [lxb_dom_document_import_node(...)](https://github.com/lexbor/lexbor/blob/master/source/lexbor/dom/interfaces/document.h#L130)
3. [lxb_html_document_import_node(...)](https://github.com/lexbor/lexbor/blob/master/source/lexbor/html/interfaces/document.h#L110)

**Comment by rushter** [comment]
@lexborisov I think you forgot to remove/complete this part:

https://github.com/lexbor/lexbor/blob/0c4010b10a922a45513d67beec0ddd29c2951f85/source/lexbor/dom/interfaces/document.c#L434-L433

**Comment by lexborisov** [comment]
@rushter 

Somehow I missed it. Removed.
Thanks for the report!

**Comment by rushter** [comment]
@lexborisov  Sorry for bothering you again, but I don't understand how to implement cloning properly.
I want to clone the whole three to an empty document.


It looks like cloning from the root node does not work.

```
node = <lxb_dom_node_t *> lxb_dom_document_root(&document.dom_document)
cloned_node = lxb_dom_document_import_node(&document.dom_document, node, True)
```

Another problem is that I can't find a function to initialize an empty document. The `lxb_html_document_parser_prepare` is inlined.

My current unfinished code:
```
        cloned_document = lxb_html_document_create()

        node = <lxb_dom_node_t *> lxb_dom_document_root(&self.document.dom_document)
        cloned_node = lxb_dom_document_import_node(&self.document.dom_document, node, True)
        lxb_dom_node_insert_after(
            <lxb_dom_node_t *> lxb_dom_document_root(&cloned_document.dom_document),
            cloned_node
        )
```
What happens to cloned nodes when I destroy the  `cloned_node` document (`lxb_html_document_destroy`)? Does it destroy the imported nodes?

**Comment by lexborisov** [comment]
@rushter 

> @lexborisov Sorry for bothering you again, but I don't understand how to implement cloning properly.
> I want to clone the whole tree to an empty document.
> 
> It looks like cloning from the root node does not work.

Fixed.

[...]
> 
> What happens to cloned nodes when I destroy the `cloned_node` document (`lxb_html_document_destroy`)? Does it destroy the imported nodes?

[document.importNode](https://dom.spec.whatwg.org/#dom-document-importnode)(node). In this case: `document` is an object into which the resulting node will be inserted later. In other words, node will use the memory from the document.
We cannot directly insert "foreign" nodes because they use "foreign" memory.

```C
document_src = lxb_html_document_create();
document_dst = lxb_html_document_create();

/* ... parse some HTML for document_src and document_dst. */

root_src = lxb_dom_document_root(lxb_dom_interface_document(document_src));
root_dst = lxb_dom_document_root(lxb_dom_interface_document(document_dst));

/* Clone src node. */

cloned = lxb_html_document_import_node(document_dst, root_src, true);

lxb_dom_node_insert_after(root_dst, cloned);

/*
 * Will not destroy the clone of the node because
 * the clone uses memory from the destination document. 
 */
lxb_html_document_destroy(document_src);
```

@rushter  thanks for using and reporting!

**Comment by rushter** [comment]
> @rushter
> 
> > @lexborisov Sorry for bothering you again, but I don't understand how to implement cloning properly.
> > I want to clone the whole tree to an empty document.
> > It looks like cloning from the root node does not work.
> 
> Fixed.
> 
> [...]
> 
> > What happens to cloned nodes when I destroy the `cloned_node` document (`lxb_html_document_destroy`)? Does it destroy the imported nodes?
> 
> [document.importNode](https://dom.spec.whatwg.org/#dom-document-importnode)(node). In this case: `document` is an object into which the resulting node will be inserted later. In other words, cloned node will use the memory from the document.
> We cannot directly insert "foreign" nodes because they use "foreign" memory.
> 
> ```c
> document_src = lxb_html_document_create();
> document_dst = lxb_html_document_create();
> 
> /* ... parse some HTML for document_src and document_dst. */
> 
> root_src = lxb_dom_document_root(lxb_dom_interface_document(document_src));
> root_dst = lxb_dom_document_root(lxb_dom_interface_document(document_dst));
> 
> /* Clone src node. */
> 
> cloned = lxb_html_document_import_node(document_dst, root_src, true);
> 
> lxb_dom_node_insert_after(root_dst, cloned);
> 
> /*
>  * Will not destroy the clone of the node because
>  * the clone uses memory from the destination document. 
>  */
> lxb_html_document_destroy(document_src);
> ```
> 
> @rushter thanks for using and reporting!

Is there a way to create an empty document object without parsing an empty string?

**Comment by lexborisov** [comment]
@rushter 

> 
> Is there a way to create an empty document without parsing an empty string?

What exactly do you mean?

```C
/* Empty Document with root node. */
document = lxb_html_document_create();

document->ready_state = LXB_HTML_DOCUMENT_READY_STATE_COMPLETE;

lxb_dom_node_insert_child(lxb_dom_interface_node(document), some_node);

```

**Comment by rushter** [comment]
> @rushter
> 
> > Is there a way to create an empty document without parsing an empty string?
> 
> What exactly do you mean?
> 
> ```c
> /* Empty Document with root node. */
> document = lxb_html_document_create();
> 
> document->ready_state = LXB_HTML_DOCUMENT_READY_STATE_COMPLETE;
> 
> lxb_dom_node_insert_child(lxb_dom_interface_node(document), some_node);
> ```

This example segfaults for me.

I use: 
```
            cloned_document = lxb_html_document_create()
            lxb_html_document_parse(cloned_document, <lxb_char_t *> '', 0)
```

**Comment by rushter** [comment]
I tried to use `lxb_dom_node_replace_all` but got an unexpected result.
Since it's not documented, it's not clear that it replaces.

```
        lxb_dom_node_replace_all(
            <lxb_dom_node_t *> lxb_dom_document_root(&cloned_document.dom_document),
            cloned_node
        )
```

When serializing the clone to HTML, I get the following:

```
In [1]: from selectolax.lexbor import LexborHTMLParser
   ...:
   ...: html_parser = LexborHTMLParser("""<h1>Welcome</h1>""")
   ...: clone = html_parser.clone()
   ...: print(clone.html)
   ...:
<html><html><head></head><body><h1>Welcome</h1></body></html></html>
```

**Comment by lexborisov** [comment]
> > @rushter
> > > Is there a way to create an empty document without parsing an empty string?
> > 
> > 
> > What exactly do you mean?
> > ```c
> > /* Empty Document with root node. */
> > document = lxb_html_document_create();
> > 
> > document->ready_state = LXB_HTML_DOCUMENT_READY_STATE_COMPLETE;
> > 
> > lxb_dom_node_insert_child(lxb_dom_interface_node(document), some_node);
> > ```
> 
> This example segfaults for me.
> 

It just can't be. 
Where does it segfault and which node are you passing on as a child (`some_node`)?

**Comment by rushter** [comment]
> > > @rushter
> > > > Is there a way to create an empty document without parsing an empty string?
> > > 
> > > 
> > > What exactly do you mean?
> > > ```c
> > > /* Empty Document with root node. */
> > > document = lxb_html_document_create();
> > > 
> > > document->ready_state = LXB_HTML_DOCUMENT_READY_STATE_COMPLETE;
> > > 
> > > lxb_dom_node_insert_child(lxb_dom_interface_node(document), some_node);
> > > ```
> > 
> > 
> > This example segfaults for me.
> 
> It just can't be.
> Where does it segfault and which node are you passing on as a child (`some_node`)?

My code In Cython (very similar to C):
```cython
        cdef lxb_html_document_t* cloned_document
        cdef lxb_dom_node_t* cloned_node

        with nogil:
            cloned_document = lxb_html_document_create()
            # lxb_html_document_parse(cloned_document, <lxb_char_t *> '', 0)
            cloned_document.ready_state = LXB_HTML_DOCUMENT_READY_STATE_COMPLETE

            cloned_node = lxb_dom_document_import_node(
                &self.document.dom_document,
                <lxb_dom_node_t *> lxb_dom_document_root(&self.document.dom_document),
                <bint> True
            )
            # lxb_dom_node_replace_all(
            #     <lxb_dom_node_t *> lxb_dom_document_root(&cloned_document.dom_document),
            #     cloned_node
            # )
            lxb_dom_node_insert_child(
                <lxb_dom_node_t * > &cloned_document,
                cloned_node,
            )
```

Both `lxb_dom_node_replace_all` and `lxb_dom_node_insert_child` segfault.

**Comment by rushter** [comment]
Sorry, nevermind, I found the problem.

**Comment by lexborisov** [comment]
> I tried to use `lxb_dom_node_replace_all` but got an unexpected result.
> Since it's not documented, it's not clear that it replaces.
> 

[lxb_dom_node_replace_all](https://dom.spec.whatwg.org/#concept-node-replace-all)(parent, node) will be remove/destroy all children from first argument node (parent) and insert second argument as child to parent.

**Comment by lexborisov** [comment]
@rushter 

> > It just can't be.
> > Where does it segfault and which node are you passing on as a child (`some_node`)?
> 
> My code In Cython (very similar to C):
> 
> ```cython
>         cdef lxb_html_document_t* cloned_document
>         cdef lxb_dom_node_t* cloned_node
> 
>         with nogil:
>             cloned_document = lxb_html_document_create()
>             cloned_document.ready_state = LXB_HTML_DOCUMENT_READY_STATE_COMPLETE
> 
>             cloned_node = lxb_dom_document_import_node(
               /* You must to use the document in which the cloned node will be used. */
               /* A node and everything in it are created from document resources. */
>                 &cloned_document.dom_document,
>                 <lxb_dom_node_t *> lxb_dom_document_root(&self.document.dom_document),
>                 <bint> True
>             )
>             # lxb_dom_node_replace_all(
>             #     <lxb_dom_node_t *> lxb_dom_document_root(&cloned_document.dom_document),
>             #     cloned_node
>             # )
>             lxb_dom_node_insert_child(
               /* Here it was get a pointer to a pointer, which is not correct. */
>                 <lxb_dom_node_t *> cloned_document,
>                 cloned_node,
>             )
> ```
> 

The code contains two errors:
1. In `lxb_dom_document_import_node()`
2. In `lxb_dom_node_insert_child()`

Please take a look my comments in code.

I wonder what problem you are solving.
Why create a blank document and clone it for all nodes ?! :)

P.S.: I advise you to write always safe code. That is, to check for memory allocation.

```C
cloned_document = lxb_html_document_create()
if (cloned_document == NULL) {
    /* return or ... */
}

cloned_node = lxb_dom_document_import_node(...)
if (cloned_document == NULL) {
    /* return or ... */
}
```

**Comment by rushter** [comment]
Thanks for the advice. 

When I was trying to get cloning working, I saw that `lxb_html_document_import_node` reuses the same document and changed my code as well to test it. I forgot to change it back.

It's pretty hard to keep track of everything when I'm trying to understand the code and the meaning of the parameters :).

> I wonder what problem you are solving.
> Why create a blank document and clone it for all nodes ?! :)

I was just trying to make a full copy of a document. It actually works even with wrong the parameter when both documents are still in memory.
